### ISSUE TITLE
Hue app crashing since 1.5 update

### ISSUE THREAD

**Issue by gvrsnor** [athombv/nl.philips.hue#82] opened 2017-09-08 06:39 UTC
Already crashed 2 times since the Homey 1.5 update (never crashed before and I only have 3 bulbs, no advanced setup).

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by WeeJeWel** [comment] 2017-09-11 11:52
Duplicate of #79

**Closed by WeeJeWel** 2017-09-11 11:52 UTC
