### ISSUE TITLE
Too many memwarns received

### ISSUE THREAD

**Issue by CyberSponk** [athombv/nl.philips.hue#79] opened 2017-08-12 06:43 UTC
**What is your Homey version (Settings → System)?**
Homey > 1.5.0-rc.5 / Hue-App > 2.2.8

**What did you try to achieve?**
Did nothing.

**What was the result?**
Lightify-Bulb connected to Hue-Bridge didn't going On or Off

**What did you expect as result?**
Bulbs going On and/or Off.

**Any other remarks**
Reported this error now 3rd time since last 3 days during die Function "Contact Developer" > No Response.

**Please attach a Homey System log (Settings -> System -> Send Log)**
D5B5D3ACF5

**Comment by CyberSponk** [comment] 2017-08-15 06:35
Doing settings > insights > delete all insights two days ago. Since this the app didn't crashes the last two days. Perhaps helps this information.

**Comment by corvdniet** [comment] 2017-08-19 07:55
I had the same error (too many memwarmns received). Only it was for SmartPresence and I'm on 1.5.0-rc.6

**Comment by daneedk** [comment] 2017-08-19 18:53
Just had the same error again on 1.5.0-rc6, Hue app version 2.2.8
Log: 802D981E4D

**Comment by daneedk** [comment] 2017-08-19 19:06
Mem usage, homey being idle.

![image](https://user-images.githubusercontent.com/16610696/29489466-24046820-8522-11e7-8d0f-0b293ce4b1ff.png)

**Comment by camilleversteeg** [comment] 2017-08-20 19:50
Same problem. I have to restart the Hue app daily. First time that i'm having issues with the app.

**Comment by WeeJeWel** [comment] 2017-08-21 16:22
I cannot reproduce the issue unfortunately. How many devices do you guys have paired, and what kind of Flows are you using?

**Comment by CyberSponk** [comment] 2017-08-21 16:47
Paired 38 Devices (or 39). Since deleting Insights every day it works fine. What you mean with "what kind of Flows"? I'm using simple Flows e.g. If Motion TurnedOn and BrightnesMotion is under 10 then TurnOn Bulb.

**Comment by daneedk** [comment] 2017-08-21 17:34
1x LST001 Hue Lightstrip
1x LWB001 LivingWhites
1x LCT001 Hue Color Lamp
11x Osram PAR16 GU10 Lightify
All firmwares are up to date.
To turn the lights on I use the 'Set a Scene' card and to turn them off I use the 'Turn all lights of in a room' card.
The flows to turn on the lights can be triggered by a kaku switch or on presence detection, the off flow is triggered by the same kaku switch. I use no hue cards in the 'and' column in different flows
I use no dimmers or Hue Tap devices.
There have been no changes in the connected lights for at least 8 months now and unfortunatly I am not sure when the problems started, the latest hue app update was installed the same day as 1.5.0_RC4.

**Comment by denniedegroot** [comment] 2017-08-21 19:03
9 Motion Sensors
7 Hue Colors
2 Hue White
3 Hue Spots
3 Hue lightstrips
Hue Go
Hue Beyond

Every motion sensors has a flow to trigger an alarm when nobody is home. It also sets a variable to remember which motion sensor it is.

And some flows to dim the lights, trigger a scene, when Plex/Kodi starts.

But I have not made any changes to the flows in the last few months.

**Comment by camilleversteeg** [comment] 2017-08-22 15:26
I (only) have about 10 devices. Btw. is it possible to get a notification when a Homey app crashes?

**Comment by corvdniet** [comment] 2017-08-23 07:50
@daneedk How did you make these graphs?

**Comment by daneedk** [comment] 2017-08-24 19:45
When you install an app manualy on your homey you get an extra option in Settings, developers, and the graphs are shown there.

**Comment by corvdniet** [comment] 2017-08-25 12:04
@daneedk Thnx

**Comment by blavla** [comment] 2017-08-26 05:59
Same over here... App is crashing about every 2 days...
I have deleted all my insights, but still it's crashing.
The log: C6C97C7EF0

**Comment by blavla** [comment] 2017-09-03 18:11
Hi, I'm still having this problem. Is this still on the radar? Can I do anything to provide more information about this?

**Comment by WeeJeWel** [comment] 2017-09-04 08:49
Yes, we are still figuring out why this is happening. I will try to downgrade the library we use and see if that fixes things.

**Comment by daneedk** [comment] 2017-09-04 14:08
@WeeJeWel I'd be happy to side load a test version, on my homey the memory growth is very visible:

![image](https://user-images.githubusercontent.com/16610696/30029838-225f8a02-918b-11e7-9e8d-8cb29715ddec.png)

**Comment by WeeJeWel** [comment] 2017-09-04 15:10
I've created a branch with HueJay at v1.5.0 instead of v1.7.0.

@daneedk Please test this for me: https://github.com/athombv/nl.philips.hue/archive/feature/downgrade-huejay.zip

**Comment by daneedk** [comment] 2017-09-04 15:52
@WeeJeWel I've just installed it, I'll keep an eye on the memory usage.

**Comment by daneedk** [comment] 2017-09-04 17:53
@WeeJeWel Don't think that's it :( 10Mb growth in 2 hours:
![image](https://user-images.githubusercontent.com/16610696/30035458-a532e9f0-91aa-11e7-9ea6-1a4519aaf417.png)

**Comment by daneedk** [comment] 2017-09-04 19:19
Had to reboot homey due to the lost connection with Athom cloud, I left the session with the graphs running and was surprised to see memory usage off all apps was much lower:
![image](https://user-images.githubusercontent.com/16610696/30036767-64eda3f6-91b6-11e7-9cf5-af6b61e8e85f.png)
![image](https://user-images.githubusercontent.com/16610696/30036769-69e79d4e-91b6-11e7-905e-29110101b980.png)
![image](https://user-images.githubusercontent.com/16610696/30036772-6ea55d08-91b6-11e7-9524-aab3ef32ce39.png)
![image](https://user-images.githubusercontent.com/16610696/30036775-72ff46e8-91b6-11e7-938a-dcecba1df269.png)
![image](https://user-images.githubusercontent.com/16610696/30036778-78f918c6-91b6-11e7-831b-84dce258c311.png)
![image](https://user-images.githubusercontent.com/16610696/30036782-7e58d78e-91b6-11e7-9d32-4dd88895c88a.png)
![image](https://user-images.githubusercontent.com/16610696/30036790-83c7ed40-91b6-11e7-83eb-775171e428f8.png)
![image](https://user-images.githubusercontent.com/16610696/30036795-87fec1fe-91b6-11e7-9769-5ead1acdbd35.png)
![image](https://user-images.githubusercontent.com/16610696/30036801-8bf9f71a-91b6-11e7-988c-e7fc0100c697.png)
![image](https://user-images.githubusercontent.com/16610696/30036805-9169e1ce-91b6-11e7-9cfd-57c63d96c434.png)

**Comment by camilleversteeg** [comment] 2017-09-05 17:18
I'm using SmartPresence but did not yet get any memory warnings. I do get Hue crashes every 7 days. I think i will set-up a Homey restart flow. 

btw. I also lost connection with the Athom cloud and I have to reboot now. First time for that as well.

Hopefully the cause can be found. It clearly started with the 1.5 beta's for all of us.

**Comment by daneedk** [comment] 2017-09-06 16:56
No reboot in the last 2 days, monitored it again today and you can still see the memory usage rising.

![image](https://user-images.githubusercontent.com/16610696/30124254-e1dabf82-9334-11e7-8b59-73e4ea838679.png)

Anything else we can do/try to beat this bug?

**Comment by WeeJeWel** [comment] 2017-09-06 16:59
Okay thanks, I'll investigate further.

**Comment by denniedegroot** [comment] 2017-09-08 14:30
Today it also crashed with the library downgrade (HueJay v1.5.0). So I think it must be something in Homey's core that's causing this.

**Comment by WeeJeWel** [comment] 2017-09-08 14:35
We've also upgraded other parts of the app so I doubt it's due to a Homey core update. I'm looking into this asap!

**Comment by Veldkornet** [comment] 2017-09-12 19:01
Got this today for the first time as well on Homey 1.5.1.  
Although I only have 3 lights connected to my Hue Bridge. 
Log: 865845F0D9

**Comment by WeeJeWel** [comment] 2017-09-13 10:41
I have updated the `master` branch with a few changes that might solve the issue. Could a few of you install that version and report if it still crashes?

**Comment by WeeJeWel** [comment] 2017-09-14 10:02
Anyone? :-)

**Comment by daneedk** [comment] 2017-09-14 10:35
Oeps, I overlooked your message, I'll install it tonight and keep you posted.

**Comment by denniedegroot** [comment] 2017-09-14 17:55
I have been running since yesterday and no crashed yet, during the weekend I will confirm if it's stable.

**Comment by daneedk** [comment] 2017-09-14 19:08
Installed the master branche, this is the first result:

![image](https://user-images.githubusercontent.com/16610696/30449952-c65f9658-9990-11e7-8dac-f359dc2eece3.png)

**Comment by daneedk** [comment] 2017-09-15 12:04
This is over a longer period:
![image](https://user-images.githubusercontent.com/16610696/30481406-b9e2cc86-9a1e-11e7-9b7a-89c6a0d8715c.png)

**Comment by denniedegroot** [comment] 2017-09-16 09:16
Still running without crashes, so for me it is stable again.

**Comment by WeeJeWel** [comment] 2017-09-16 16:22
Brilliant, thanks for testing. I've updated the app in the App Store and I hope this issue is now resolved.

**Comment by denniedegroot** [comment] 2017-09-16 21:50
Nooo...the app just crashed :(
The memory usage was 109MB before crashing again.

**Comment by daneedk** [comment] 2017-09-18 19:17
No crash for me, but memory still steadily growing
![image](https://user-images.githubusercontent.com/16610696/30559983-c037a620-9cb6-11e7-8b30-33a69af01c16.png)

**Comment by caseda** [comment] 2017-09-19 22:36
Today had a toomany memwarn on latest hue update as well.

**Comment by WeeJeWel** [comment] 2017-09-20 09:41
Auch! Back to square one...

**Comment by caseda** [comment] 2017-09-20 09:45
Maybe start using (/create) a module that uses promises, increases stability as well 😛

**Comment by WeeJeWel** [comment] 2017-09-20 09:52
Yeah I'm just going to rewrite to SDK2, adds support for transitions as well :)

**Comment by blavla** [comment] 2017-09-23 10:39
For the time being I made a flow that runs daily and restart the hue-app with 2 lines of HomeyScript :-)

`Homey.apps.restartApp({'id':'nl.philips.hue', 'data':{}});`
`return true`

**Comment by WeeJeWel** [comment] 2017-09-25 18:38
I have completely written the app to SDKv2, and hopefully any memory leaks should be gone.

Could you guys check it out? It's on the `feature/sdk2` branch. Download the zip and run with `athom project --run`. All lights will still be there.

@blavla @caseda @daneedk @denniedegroot @camilleversteeg @corvdniet @CyberSponk

**Comment by WeeJeWel** [comment] 2017-09-25 18:40
As a bonus, dimming over time is now available from the Flow Editor natively :-)

![screen shot 2017-09-25 at 20 40 30](https://user-images.githubusercontent.com/319873/30825023-c90890e0-a231-11e7-975d-3092a698d928.png)

**Comment by daneedk** [comment] 2017-09-25 18:46
Sorry, no can do right now, 1800 km's from home enjoying ouzo's 😜

**Comment by denniedegroot** [comment] 2017-09-25 19:41
@WeeJeWel 1.5.3 automatically restarts the app if it crashed, how do we know if the app didn't crash and is stable?

**Comment by WeeJeWel** [comment] 2017-09-25 19:42
You'll see the memory log grow and then eventually reduce instantly.

Also sending me a system log in a few days will do the trick :)

**Comment by WeeJeWel** [comment] 2017-09-26 09:49
Version 3.0.0 is now released to the app store as bèta. Install it here: https://apps.athom.com/app/nl.philips.hue

If it crashed I'll get automatically notified.

**Comment by CyberSponk** [comment] 2017-10-02 18:17
Homey 1.5.3 + Hue-App 3.0.1 > Last Days no Warning. For me this Issue can be closed.

**Comment by caseda** [comment] 2017-10-02 18:18
same here with last hue update, no mem warning crashes

**Comment by jeroenvollenbrock** [comment] 2017-10-30 22:43
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.

**Closed by jeroenvollenbrock** 2017-10-30 22:43 UTC
